title: soma0sd Github Page
email: soma0sd@gmail.com
baseurl: ""
url: ""
github_username: soma0sd

repositories:
  - CNU-Computer-Physics/CNU-Computer-Physics.github.io
  - CNU-Computer-Physics/Example-and-Practice

plugins:
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-relative-links

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false

relative_links:
  enabled: true
  collections: false
