# title: soma0sd Github Page
# author: soma0sd
# email: soma0sd@gmail.com

title: soma0sd 깃허브 페이지
author: soma0sd
email: soma0sd@gmail.com
url: "https://soma0sd.github.io/"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

# jekyll-seo-tag PLugin
webmaster_verifications:
  google: XyHLbga2Eq2JzK-hhFHlpl5XQHWqc8jDEZV5hczQ7J0
  bing: 55B06ED5B745AF3AC11DE920FEC21E9D
locale: ko_Kr
